export default () => ({
  items: [
    {
      title: 'Wydarzenie 1',
      id: 1,
      date: '2021-05-14',
      city: 'Warszawa',
      invitedIds: [],
    },
    {
      title: 'Wydarzenie 2',
      id: 2,
      date: '2021-05-15',
      city: 'Warszawa',
      invitedIds: [],
    },
    {
      title: 'Wydarzenie 3',
      id: 3,
      date: '2021-05-16',
      city: 'Warszawa',
      invitedIds: [],
    },
    {
      title: 'Wydarzenie 4',
      id: 4,
      date: '2021-06-17',
      city: 'Kraków',
      invitedIds: [],
    },
    {
      title: 'Wydarzenie 5',
      id: 5,
      date: '2021-06-17',
      city: 'Kraków',
      invitedIds: [],
    },
    {
      title: 'Wydarzenie 6',
      id: 6,
      date: '2021-06-18',
      city: 'Kraków',
      invitedIds: [],
    },
    {
      title: 'Wydarzenie 7',
      id: 7,
      date: '2021-06-18',
      city: 'Lublin',
      invitedIds: [],
    },
    {
      title: 'Wydarzenie 8',
      id: 8,
      date: '2021-06-18',
      city: 'Lublin',
      invitedIds: [],
    },
    {
      title: 'Wydarzenie 9',
      id: 9,
      date: '2021-06-17',
      city: 'Lublin',
      invitedIds: [],
    },
    {
      title: 'Wydarzenie 10',
      id: 10,
      date: '2021-06-17',
      city: 'Lublin',
      invitedIds: [],
    },
  ],
})
